repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format (local)
        entry: python tools/run-clang-format.py --color always -i
        language: system
        types: [file]
        files: \.(cpp|cc|cxx|h|hpp|hh|slang|slangh)$
        exclude: ^(?!.*(src|tests)/)